### ISSUE TITLE
Add web scraping scripts

### ISSUE THREAD

**Issue by harshareddy794** [harshareddy794/HACKTOBERFEST2020#113]
Add web scraping scripts.
It can be using beautiful soup, selenium, request, or scrappy you can use any of these libraries

**Comment by SARTHAK-27** [comment]
@harshareddy794  I have a basic template with examples for Beautiful Soup, if you want I can add that Python file.

**Comment by harshareddy794** [comment]
Yeah @SARTHAK-27 
Go ahead and add

**Comment by SARTHAK-27** [comment]
Should I make a new folder(Web Scrapping) in Python or somewhere else?

**Comment by harshareddy794** [comment]
Make a folder in python folder itself @SARTHAK-27

**Comment by SARTHAK-27** [comment]
@harshareddy794  I have added the Beautiful Soup File. My pull request number is 170.

**Comment by harshareddy794** [comment]
I will close all pending PRs which got reviewed and request ed for change by tomorrow 
Make an appropriate change and tag me in a comment in your PR to re-review your PR
